title: "Kim Tran Restaurant"
logo: /assets/img/logo.png
description: "Chinese and Vietnamese Food\nMonday - Saturday, 11:00 A.M. - 2:30 P.M. & 5:00 P.M. - 9:30 P.M.\n1015 Rittiman Rd #107, San Antonio, TX 78218\n(210) 824-4660"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

address: "Address: 1015 Rittiman Rd #107, San Antonio, TX 78218"
phone: "Phone: (210) 824-4660"
