title: Kim Tran Restaurant
logo: /assets/img/logo.png
description: Chinese and Vietnamese Food
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

hours: Monday - Saturday: 11:00 A.M. - 2:30 P.M. & 5:00 P.M. - 9:30 P.M.
address: 1015 Rittiman Rd \#107, San Antonio, TX 78218
phone: (210) 824-4660
